### ISSUE TITLE
Question - How to list hosts defined?

### ISSUE THREAD

**Issue by gvastel** [ITRS-Group/cordial#42]
`geneos ls` does not list hosts.  Did not see any other command that could list hosts defined.  Is there one?
If no, it would be a good to have.

**Comment by pgalbavy-itrs** [comment]
`geneos ls hosts` - hosts have different configurations and settings, which was not always the case, so the columns would have different meanings.


Peter Galbavy
Service Delivery Consultant
***@***.***
www.itrsgroup.com
ITRS Group Ltd
15 Bonhill Street,
​London, EC2A 4DN
Mob.+44 7710 348988
Internet communications are not secure and therefore the ITRS Group does not accept legal responsibility for the contents of this message. Any view or opinions presented are solely those of the author and do not necessarily represent those of the ITRS Group unless otherwise specifically stated.
[itrs.email.signature]
From: Gerard V. ***@***.***>
Sent: 17 November 2022 06:15
To: ITRS-Group/cordial ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ITRS-Group/cordial] Question - How to list hosts defined? (Issue #42)


geneos ls does not list hosts. Did not see any other command that could list hosts defined. Is there one?
If no, it would be a good to have.

**Comment by pgalbavy-itrs** [comment]
There may also be a case for allowing reverse syntax for 'aes' and 'tls' so that `geneos ls aes` and `geneos aes ls` work and then `geneos host ls` may also make sense, but not yet.
